export const JobActionTypes = {
    SET_CURRENT_JOB_ID: 'SET_CURRENT_JOB_ID',
    SET_CURRENT_JOB_ADDRESS: 'SET_CURRENT_JOB_ADDRESS',
    SET_CURRENT_JOB_DESCRIPTION: 'SET_CURRENT_JOB_DESCRIPTION',
    SET_CURRENT_JOB_START: 'SET_CURRENT_JOB_START',
    SET_CURRENT_JOB_FINISH: 'SET_CURRENT_JOB_FINISH'
}